# These are some additions to the web_steps.rb file generated by cucumber-rails.

require 'uri'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))

Given /^(?:|I )(?:am|start) (?:on|at) (.+)$/ do |page_name|
  visit path_to(page_name)
end

When /^(?:|I )(?:press|click on) the "([^\"]*)" button$/ do |button|
  click_button(button)
end

When /^(?:|I )check the "([^\"]*)" (?:|check)box$/ do |field|
  check(field)
end

When /^(?:|I )(?:un|don't |DON'T |do not |do NOT |DO NOT )check "([^\"]*)"$/ do |field|
  uncheck(field)
end

When /^(?:|I )(?:un|don't |DON'T |do not |do NOT |DO NOT )check the "([^\"]*)" (?:|check)box$/ do |field|
  uncheck(field)
end

Then /^(?:|I )should (?:not|NOT) see "([^\"]*)"$/ do |text|
  response.should_not contain(text)
end

Then /^(?:|I )should (?:not|NOT) see "([^\"]*)" within "([^\"]*)"$/ do |text, selector|
  within(selector) do |content|
    content.should_not contain(text)
  end
end

Then /^(?:|I )should (?:not|NOT) see \/([^\/]*)\/$/ do |regexp|
  regexp = Regexp.new(regexp)
  response.should_not contain(regexp)
end

Then /^(?:|I )should (?:not|NOT) see \/([^\/]*)\/ within "([^\"]*)"$/ do |regexp, selector|
  within(selector) do |content|
    regexp = Regexp.new(regexp)
    content.should_not contain(regexp)
  end
end

Then /^the "([^\"]*)" field should (?:not|NOT) contain "([^\"]*)"$/ do |field, value|
  field_labeled(field).value.should_not =~ /#{value}/
end

Then /^the "([^\"]*)" checkbox should (?:not|NOT) be checked$/ do |label|
  field_labeled(label).should_not be_checked
end

Then /^(?:|I )should (?:|still )(?:be|end up|get redirected|be redirected|redirect|stay)(?: at| on| to) (.+)$/ do |page_name|
  URI.parse(current_url).path.should == path_to(page_name)
end
